### ISSUE TITLE
input credentials

### ISSUE THREAD

**Issue by Marcello1** [sidoh/words_with_robots#1]
Trying to input my facebook credentials in the robotsettingskey.java & robotsettings.java and unsure where to place them... any help??

**Comment by sidoh** [comment]
You don't need to change the code. Just run it, it'll prompt. I very much doubt the part that scrapes the access token for you works anymore. Facebook changes that kind of thing way too often. It's easier to get the zynga access token by opening a game in the browser, opening dev tools, and looking for a request to zynga (the ones that end in `.json` usually). It'll be in the headers. `X-Access-Token:` or something like that.

**Comment by Marcello1** [comment]
I thought you can type your facebook credentials... nothing is coming up when i compile it in eclipse.

**Comment by sidoh** [comment]
You can, but it probably doesn't work anymore.

I'm not familiar with Eclipse, but it should prompt via stdin if you run `org.sidoh.words_with_robots.WwfConsole`.

**Comment by Marcello1** [comment]
When i try and run that via eclipse, I get the following errors;

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/fanm/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/fanm/.m2/repository/org/slf4j/slf4j-simple/1.5.8/slf4j-simple-1.5.8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" java.lang.NullPointerException
	at org.sidoh.wwf_api.AccessTokenRetriever.promptForAccessToken(AccessTokenRetriever.java:57)
	at org.sidoh.words_with_robots.WwfConsole.main(WwfConsole.java:283)

**Comment by sidoh** [comment]
This could basically only happen if whatever environment you're running it in (Eclipse) doesn't support stdin:

```
  public String promptForAccessToken() throws IOException {
    Console console = System.console();

    return getAccessToken(console.readLine("Facebook username: "),
      String.valueOf(console.readPassword("Facebook password: ")));
  }
```

Probably best to find the access token via dev tools like I described before.
